# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------
name = "Gatsby"
link = "http://gatsby.icu"
avatar = "/images/avatar.png"
