# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------
name = "Gatsby Van"
email = "gatsby_van@163.com"
link = "gatsby.icu"
avatar = "/images/avatar.png"
