# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------
name = "Gatsby"
# email = "gatsby_van@163.com"
link = "http://gatsby.icu"
avatar = "/images/avatar.png"
