# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------
title = "Gatsby's Notes"
# Hostname (and path) to the root
baseURL = "http://localhost:1313"
# Default theme to be use when building the site with Hugo
theme = "FixIt"
# determines default content language ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "en"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# Timezone Local
timeZone = "Asia/Shanghai"
# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = true
# whether to use emoji code
enableEmoji = true
# the editor to use when creating new content
newContentEditor = "code"
# whether to capitalize automatic list titles
titleCaseStyle = "ap"
capitalizeListTitles = false
# whether build drafts
buildDrafts = false
# whether use relative URLs
relativeURLs = false
# Length of post summery
summaryLength = 150
# ignore some build errors
ignoreLogs = [
  "error-get-remote-json",
  "error-get-gh-repo",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken",
  "err-youtube-remote",
  "warning-dev-version"
]