# -------------------------------------------------------------------------------------
# Multilingual Configuration
# -------------------------------------------------------------------------------------
[en]
  weight = 1
  languageCode = "en"
  languageName = "English"
  hasCJKLanguage = false
  copyright = 'This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.'

[zh-cn]
  weight = 2
  languageCode = "zh-CN"
  languageName = "简体中文"
  hasCJKLanguage = true
  copyright = '本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh">知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议</a>进行许可。'