# -------------------------------------------------------------------------------------
# Markup related configuration in Hugo
# See: https://gohugo.io/getting-started/configuration-markup/
# -------------------------------------------------------------------------------------

# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNos = true
  lineNumbersInTable = true
  # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
  noClasses = false

# Goldmark is from Hugo 0.60 the default library used for Markdown
[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.renderer]
    # whether to use HTML tags directly in the document
    unsafe = true

# Table Of Contents settings
[markup.tableOfContents]
  startLevel = 2
  endLevel = 6