# -------------------------------------------------------------------------------------
# Menu Configuration (English)
# See: https://fixit.lruihao.cn/theme-documentation-basics/#menu-advanced-configuration
# -------------------------------------------------------------------------------------
[[main]]
  weight = 1
  identifier = "posts"
  pre = ""
  post = ""
  name = "Posts"
  url = "/posts/"
  title = ""

[[main]]
  weight = 2
  identifier = "tags"
  pre = ""
  post = ""
  name = "Tags"
  url = "/tags/"
  title = ""

[[main]]
  weight = 3
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""

[[main]]
  weight = 4
  identifier = "about"
  pre = ""
  post = ""
  name = "About"
  url = "/about/"
  title = ""
