# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# FixIt theme version
version = "0.2.X"
# site description
description = "Gatsby's Notes"
# site keywords
keywords = ["Gatsby", "Hugo", "FixIt"]
# site default theme ["light", "dark", "auto"]
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
gitRepo = "https://github.com/gatsby0203/gatsby.icu"
# which hash function used for SRI, when empty, no SRI is used
# ["sha256", "sha384", "sha512", "md5"]
fingerprint = ""
# date format
dateFormat = "2006-01-02"
# website title for Open Graph and Twitter Cards
title = "gatsby.icu"
# website images for Open Graph and Twitter Cards
images = ["/favicon.svg"]
# NEW enable PWA
enablePWA = false
# whether to add external Icon for external links automatically
externalIcon = false
# FixIt will, by default, inject a theme meta tag in the HTML head on the home page only.
# You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch FixIt's popularity on the rise.
disableThemeInject = false

# App icon config
[app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "gatsby.icu"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"
  # Android browser theme color
  [app.themeColor]
    light = "#f8f8f8"
    dark = "#252627"

# Header config
[header]
  # desktop header mode ["sticky", "normal", "auto"]
  desktopMode = "sticky"
  # mobile header mode ["sticky", "normal", "auto"]
  mobileMode = "auto"
  # Header title config
  [header.title]
    # URL of the LOGO
    logo = "/logo.svg"
    # title name
    name = "gatsby.icu"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    # whether to use typeit animation for title name
    typeit = true
  # Header subtitle config
  [header.subtitle]
    # subtitle name
    name = ""
    # whether to use typeit animation for subtitle name
    typeit = false

# Breadcrumb config
[breadcrumb]
  enable = false
  sticky = false
  showHome = false

# Footer config
[footer]
  enable = true
  # Custom content (HTML format is supported)
  # For advanced use, see parameter `params.customFilePath.footer`
  custom = ""
  # whether to show Hugo and theme info
  hugo = true
  # whether to show copyright info
  copyright = true
  # whether to show the author
  author = true
  # Site creation year
  since = 2023
  # license info (HTML format is supported)
  license = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" align="center" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/80x15.png" /></a>'
  # Public network security only in China (HTML format is supported)
  gov = ""
  # ICP info only in China (HTML format is supported)
  icp = ""
  [footer.siteTime]
    enable = true
    animate = true
    icon = "fa-solid fa-heartbeat"
    pre = ""
    value = "2023-04-16T00:00:00+08:00"
  # footer lines order, optional values: ["first", 0, 1, 2, 3, 4, 5, "last"]
  [footer.order]
    powered = 3
    copyright = 3
    statistics = 2
    visitor = 1
    beian = 4

# Section (all posts) page config
[section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10
  # recently updated posts settings
  [section.recentlyUpdated]
    enable = false
    rss = false
    days = 30
    maxCount = 10

# List (category or tag) page config
[list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

# TagCloud config for tags page
[tagcloud]
  enable = true
  min = 14 # Minimum font size in px
  max = 32 # Maximum font size in px
  peakCount = 10 # Maximum count of posts per tag
  orderby = "name" # Order of tags, optional values: ["name", "count"]

# Page global config
[page]
  # whether to enable the author's avatar of the post
  authorAvatar = true
  # whether to hide a page from home page
  hiddenFromHomePage = false
  # whether to hide a page from search results
  hiddenFromSearch = false
  # whether to enable twemoji
  twemoji = true
  # whether to enable lightgallery
  # if set to "force", images in the content will be forced to shown as the gallery.
  lightgallery = true
  # whether to enable the ruby extended syntax
  ruby = true
  # whether to enable the fraction extended syntax
  fraction = true
  # whether to enable the fontawesome extended syntax
  fontawesome = true
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
  # whether to show link to Raw Markdown content of the content
  linkToMarkdown = false
  # whether to show the full text content in RSS
  rssFullText = false
  # Page style ["narrow", "normal", "wide", ...]
  pageStyle = "normal"
  # Auto Bookmark Support
  # If true, save the reading progress when closing the page.
  autoBookmark = false
  # whether to enable wordCount
  wordCount = true
  # whether to enable readingTime
  readingTime = true
  # end of post flag
  endFlag = ""
  # whether to enable instant.page
  instantPage = false
  # Repost config
  [page.repost]
    enable = false
    url = ""
  # Table of the contents config
  [page.toc]
    # whether to enable the table of the contents
    enable = true
    # whether to keep the static table of the contents in front of the post
    keepStatic = true
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
    # position of TOC ["left", "right"]
    position = "right"
  # Display a message at the beginning of an article to warn the reader that its content might be expired
  [page.expirationReminder]
    enable = true
    # Display the reminder if the last modified time is more than 90 days ago
    reminder = 90
    # Display warning if the last modified time is more than 180 days ago
    warning = 180
    # If the article expires, close the comment or not
    closeComment = false
  # KaTeX mathematical formulas
  [page.math]
    enable = true
    # default inline delimiter is $ ... $ and \( ... \)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true
  # Code config
  [page.code]
    # whether to show the copy button of the code block
    copy = true
    # whether to show the edit button of the code block
    edit = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 50
  [page.edit]
    enable = false
    # Link for fork & edit
    # url = "/edit/branch-name/subdirectory-name" # base on `gitRepo`
    # url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # full url
    url = ""
  # Mapbox GL JS config (https://docs.mapbox.com/mapbox-gl-js)
  [page.mapbox]
    # access token of Mapbox GL JS
    accessToken = ""
    # style for the light theme
    lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
    # style for the dark theme
    darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
    # whether to add NavigationControl (https://docs.mapbox.com/mapbox-gl-js/api/#navigationcontrol)
    navigation = true
    # whether to add GeolocateControl (https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)
    geolocate = true
    # whether to add ScaleControl (https://docs.mapbox.com/mapbox-gl-js/api/#scalecontrol)
    scale = true
    # whether to add FullscreenControl (https://docs.mapbox.com/mapbox-gl-js/api/#fullscreencontrol)
    fullscreen = true
  # Donate (Sponsor) settings
  [page.reward]
    enable = true
    animation = true
    # position relative to post footer, optional values: ["before", "after"]
    position = "before"
    comment = "Buy me a coffee"
    # display mode of QR code images, optional values: ["static", "fixed"], default: `static`
    mode = "fixed"
    [page.reward.ways]
      wechatpay = "/images/wechatpay.png"
      alipay = "/images/alipay.png"
      paypal = "/images/paypal.png"
      # bitcoin = "/images/bitcoin.png"
  # social share links in post page
  [page.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true
    Whatsapp = true
    HackerNews = true
    Reddit = true
    Line = true
    Weibo = true
    # Baidu = true
  # Third-party library config
  [page.library]
    [page.library.css]
      # someCSS = "some.css"
      # located in "assets/"
      # Or
      # someCSS = "https://cdn.example.com/some.css"
    [page.library.js]
      # someJavascript = "some.js"
      # located in "assets/"
      # Or
      # someJavascript = "https://cdn.example.com/some.js"
  # Page SEO config
  [page.seo]
    # image URL
    images = []
    # Publisher info
    [page.seo.publisher]
      name = "Gatsby"
      logoUrl = "/images/avatar.png"

# TypeIt config
[typeit]
  # typing speed between each step (measured in milliseconds)
  speed = 100
  # blinking speed of the cursor (measured in milliseconds)
  cursorSpeed = 1000
  # character used for the cursor (HTML format is supported)
  cursorChar = "|"
  # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
  duration = -1
  # whether your strings will continuously loop after completing
  loop = false

# Mermaid config
[mermaid]
  # Mermaid theme, ['default', 'neutral', 'dark', 'forest', 'base']. For detail, see https://mermaid-js.github.io/mermaid/#/Setup?id=theme
  themes = ['forest', 'dark']

# PanguJS config
[pangu]
  # For Chinese writing
  enable = true
  selector = "article"

# Watermark config
# Detail config see https://github.com/Lruihao/watermark#readme
[watermark]
  enable = false
  # watermark's text (HTML format is supported)
  content = ""
  # watermark's transparency
  opacity = 0.1
  # parent of watermark's container
  appendTo = ".wrapper>main"
  # watermark's width. unit: px
  width = 150
  # watermark's height. unit: px
  height = 20
  # row spacing of watermarks. unit: px
  rowSpacing = 60
  # col spacing of watermarks. unit: px
  colSpacing = 30
  # watermark's tangent angle. unit: deg
  rotate = 15
  # watermark's fontSize. unit: rem
  fontSize = 0.85
  # watermark's fontFamily
  fontFamily = "inherit"

# Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
[verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

#Site SEO config
[seo]
  # image URL
  image = ""
  # thumbnail URL
  thumbnailUrl = "/logo.png"

# Analytics config
[analytics]
  enable = false
  # Google Analytics
  [analytics.google]
    id = ""
    # whether to anonymize IP
    anonymizeIP = true
  # Fathom Analytics
  [analytics.fathom]
    id = ""
    # server url for your tracker if you're self hosting
    server = ""

# Cookie consent config
[cookieconsent]
  enable = true
  # text strings used for Cookie consent banner
  [cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# Compatibility config
[compatibility]
  # whether to use Polyfill.io to be compatible with older browsers
  polyfill = false
  # whether to use object-fit-images to be compatible with older browsers
  objectFit = false

# GitHub banner in the top-right or top-left corner
[githubCorner]
  enable = true
  permalink = "https://github.com/gatsby0203/gatsby.icu"
  title = "View source on GitHub"
  position = "left" # ["left", "right"]

#Gravatar config
[gravatar]
  enable = true
  # Gravatar host, default: "www.gravatar.com"
  host = "www.gravatar.com" # ["cn.gravatar.com", "gravatar.loli.net", ...]
  style = "mp" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]

# Back to top
[backToTop]
  enable = true
  # Scroll percent label in b2t button
  scrollpercent = true

# Reading progress bar
[readingProgress]
  enable = true
  # Available values: ["left", "right"]
  start = "left"
  # Available values: ["top", "bottom"]
  position = "top"
  reversed = false
  light = "#000"
  dark = "#fff"
  height = "2px"

# FixIt 0.2.17 | NEW Progress bar in the top during page loading.
# For more information: https://github.com/CodeByZach/pace
[pace]
  enable = true
  # All available colors:
  # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
  color = "purple"
  # All available themes:
  # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
  # "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
  theme = "minimal"

# FixIt 0.2.17 | NEW Define custom file paths
# Create your custom files in site directory `layouts/partials/custom` and uncomment needed files below
[customFilePath]
  # aside = "custom/aside.html"
  profile = "custom/profile.html"
  # footer = "custom/footer.html"

# Developer options
[dev]
  enable = false
  # Check for updates
  c4u = false
  # Please do not expose to public!
  githubToken = ""
  # Mobile Devtools confi
  [dev.mDevtools]
    enable = false
    # "vConsole", "eruda" supported
    type = "vConsole"
