# -------------------------------------------------------------------------------------
# Theme Core Configuration (English)
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

# Search config
[search]
  enable = true
  # type of search engine ["lunr", "algolia", "fuse"]
  type = "algolia"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # max number of results length
  maxResultLength = 10
  # snippet length of the result
  snippetLength = 30
  # HTML tag name of the highlight part in results
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false
  [search.algolia]
    index = "index.en"
    appID = "67YOP0R4NM"
    searchKey = "f4a149a3fd525b6dc694078b9862da3e"
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

# Home page config
[home]
  # amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.png"
    # identifier of avatar menu link
    avatarMenu = ""
    # title shown in home page (HTML format is supported)
    title = "Gatsby's Notes"
    # subtitle shown in home page (HTML format is supported)
    subtitle = ""
    # whether to use typeit animation for subtitle
    typeit = false
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 6

# Social config about the author
[social]
  GitHub = "gatsby0203"
  Twitter = "gatsby_van"
  Instagram = "gatsby.van"
  Facebook = "gatsby0203"
  Telegram = "Gatsby_Van"
  Email = "mail.gatsby.icu"
  RSS = true