# -------------------------------------------------------------------------------------
# Basic Configuration
# Hugo Configuration See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

baseURL = "http://gatsby.icu"