# -------------------------------------------------------------------------------------
# Theme Core Configuration
# See: https://fixit.lruihao.cn/theme-documentation-basics/#site-configuration
# -------------------------------------------------------------------------------------

[page.comment]
  enable = true
  # Waline comment config (https://waline.js.org)
  [page.comment.waline]
    enable = true
    serverURL = "https://comment.gatsby.icu"
    pageview = false
    emoji = ["//unpkg.com/@waline/emojis@1.1.0/tw-emoji"]
    meta = ["nick", "mail", "link"]
    requiredMeta = ["nick", "mail"]
    login = "enable"
    wordLimit = 0
    pageSize = 10
    imageUploader = false
    highlighter = true
    comment = true
    texRenderer = true
    search = false
    recaptchaV3Key = ""
    reaction = false

# FixIt 0.3.10 | NEW Busuanzi count
[busuanzi]
  # whether to enable busuanzi count
  enable = true
  # busuanzi count core script source. Default is https://vercount.one/js
  source = "https://vercount.one/js"
  # whether to show the site views
  siteViews = true
  # whether to show the page views
  pageViews = true

# CDN config for third-party library files
[cdn]
  # CDN data file name, disabled by default ["jsdelivr.yml", "unpkg.yml", ...]
  # located in "themes/FixIt/assets/data/cdn/" directory
  # you can store your own data files in the same path under your project: "assets/data/cdn/"
  data = ""
