name: Generate an animated github chart (SNK)

on:
  schedule: # every 24 hours
    - cron: "0 0 * * *"  

  workflow_dispatch:
  # run on every push on the main branch
  push:
    branches:
    - main
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/images/github-snake.svg
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Gatsby Van
          author_email: gatsby_van@163.com
          message: ':recycle: Update Contribution Snake'
